services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: home-runner
    restart: unless-stopped
    environment:
      REPO_URL: https://github.com/jbrmmg/Home
      RUNNER_TOKEN: ACY7E263H26HWXREQBLIZR3KGAET6
      RUNNER_NAME: home-prod
      RUNNER_WORKDIR: /tmp/runner/work
      LABELS: self-hosted,home-prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-work:/tmp/runner/work

volumes:
  runner-work: