services:
  home-dev:
    image: nexus.jbrmmg.me.uk:8084/home-dev:latest
    container_name: home-dev
    restart: unless-stopped
    ports:
      - "1025:1025"
    volumes:
      - /var/lib/home/data:/app/data
    environment:
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_KEY=${EMAIL_KEY}
    networks:
      jbr-network:
        aliases:
          - home

networks:
  jbr-network:
    external: true