services:
  home:
    image: nexus.jbrmmg.me.uk:8084/home:latest
    container_name: home
    restart: unless-stopped
    ports:
      - "12036:12036"
      - "1025:1025"
    environment:
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_KEY=${EMAIL_KEY}
    volumes:
      - /var/log/jbr:/var/log/jbr
