services:
  home:
    image: nexus.jbrmmg.me.uk:8084/home:latest
    container_name: home
    restart: unless-stopped
    ports:
      - "1025:1025"
    volumes:
      - /var/lib/home/data:/app/data
    environment:
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_KEY=${EMAIL_KEY}
    networks:
      - jbr-network

networks:
  jbr-network:
    external: true
