logging:
  level:
    ROOT: info

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS TEST;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

  h2:
    console:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
