server:
  port: 12036

logging:
  level:
    ROOT: info

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./data/home;AUTO_SERVER=TRUE
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

home:
  station-merges:
    - - Moorgate
      - Liverpool Street
    - - Paddington
      - Paddington (H&C Line)-Underground
    - - Bank
      - Monument
  allowed-recipients:
    - jason@jbrmmg.me.uk
    - martina@jbrmmg.me.uk
    - cian@jbrmmg.me.uk
    - thomas@jbrmmg.me.uk
  email:
    port: 1025
    max: 30
    smtp-host: smtp.zoho.eu
    smtp-port: 587
    smtp-sender: system@jbrmmg.me.uk
    smtp-password: ${SMTP_PASSWORD}
    key: ${EMAIL_KEY}
